/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as cardSol from "./Card.sol";
export { Collection__factory } from "./Collection__factory";
export { Main__factory } from "./Main__factory";
