/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cardSol from "./Card.sol";
export type { cardSol };
export type { Collection } from "./Collection";
export type { Main } from "./Main";
export * as factories from "./factories";
export type { Card } from "./Card.sol/Card";
export { Card__factory } from "./factories/Card.sol/Card__factory";
export type { ERC721 } from "./Card.sol/ERC721";
export { ERC721__factory } from "./factories/Card.sol/ERC721__factory";
export type { IERC721 } from "./Card.sol/IERC721";
export { IERC721__factory } from "./factories/Card.sol/IERC721__factory";
export type { IERC721Receiver } from "./Card.sol/IERC721Receiver";
export { IERC721Receiver__factory } from "./factories/Card.sol/IERC721Receiver__factory";
export { Collection__factory } from "./factories/Collection__factory";
export { Main__factory } from "./factories/Main__factory";
